# Generated by Django 4.1.7 on 2023-02-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_intern_delete_internships'),
    ]

    operations = [
        migrations.CreateModel(
            name='interns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internship_name', models.CharField(default='', max_length=122)),
                ('company_name', models.CharField(default='', max_length=122)),
                ('location', models.CharField(default='', max_length=122)),
                ('CTC', models.CharField(default='', max_length=122)),
                ('type', models.CharField(default='', max_length=122)),
                ('apply_link', models.CharField(default='', max_length=122)),
                ('duration', models.CharField(default='', max_length=122)),
                ('upload_duration', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='internship',
            name='CTC',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='apply_link',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='company_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='location',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='type',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='internship',
            name='upload_duration',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='CTC',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='apply_link',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='company_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='internship_name',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='location',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='intern',
            name='type',
            field=models.CharField(default='', max_length=122),
        ),
    ]
